export const articleBodyHtmlSx = {
  color: "text.secondary",
  "& img": { maxWidth: "100%", height: "auto", borderRadius: "12px" },
  "& p": { margin: "0 0 1em" },
  overflowWrap: "anywhere",
  wordBreak: "break-word",
  "& a": {
    overflowWrap: "anywhere",
    wordBreak: "break-word",
    textDecoration: "underline",
  },
  "& pre": {
    bgcolor: "#f7f7f7",
    borderRadius: 2,
    color: "text.primary",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: "0.875rem",
    lineHeight: 1.7,
    m: "0 0 1em",
    overflowX: "auto",
    p: 1.5,
    whiteSpace: "pre",
  },
  "& code": {
    backgroundColor: "#f7f7f7",
    borderRadius: 1,
    color: "text.primary",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: "0.9em",
    px: 0.5,
    py: 0.125,
  },
  "& pre code": {
    backgroundColor: "transparent",
    borderRadius: 0,
    color: "inherit",
    fontSize: "inherit",
    p: 0,
  },
}
